#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Careers 9-20: Nursing, Dental"""

CAREERS_9_20 = []

CAREERS_9_20.append([
    "Registered Nurse", "Nursing", "Healthcare",
    "RN; Staff Nurse; Floor Nurse; Bedside Nurse",
    "Registered nurses provide and coordinate patient care, educate patients about health conditions, and offer emotional support.",
    "RNs assess patient health needs, develop nursing care plans, administer medications and treatments, monitor patient progress, and collaborate with physicians. They work across many specialties and serve as patient advocates ensuring quality care delivery.",
    "Assess and monitor patient conditions; Administer medications and treatments; Maintain patient records; Collaborate with healthcare teams; Educate patients and families; Provide emotional support and advocacy",
    "Implementing evidence-based nursing protocols; Developing patient education programs; Managing infection control initiatives; Participating in quality improvement projects; Mentoring nursing students",
    "Hospitals; Clinics; Nursing homes; Home health agencies; Community health centers; Schools",
    "36-48", "None", "Moderate", "Fair",
    "Bachelor of Science in Nursing (BSN) or Associate Degree in Nursing (ADN)",
    "BSN; ADN; MSN", "Nursing; Health Sciences",
    "Biology; Chemistry; Anatomy; Physiology; Mathematics; English",
    "NCLEX-RN",
    "Registered Nurse License (state); BLS Certification",
    "BLS; ACLS; PALS; National Certification in Specialty Area",
    "Patient assessment; Medication administration; Wound care; IV therapy; Vital sign monitoring; Patient education",
    "Empathy; Communication; Teamwork; Attention to detail; Critical thinking; Stamina",
    "Specialty nursing certifications; Informatics; Research; Case management; Public health",
    "Stethoscope; Blood pressure cuff; Syringes; IV equipment; Infusion pumps; Glucometer",
    "Electronic Health Records (Epic/Cerner); Barcode medication administration; Patient monitoring systems",
    "NULL", "Very High", "6% (Faster than average)", "No", "Low",
    "Hospitals; Clinics; Long-term care facilities; Home health agencies; Schools; Government agencies",
    "HCA Healthcare; Kaiser Permanente; Mayo Clinic; Cleveland Clinic; Ascension Health",
    "65000", "80000", "95000", "120000", "USD",
    "Staff Nurse; Graduate Nurse", "Charge Nurse; Specialty Nurse; Case Manager",
    "Nurse Manager; Clinical Nurse Specialist",
    "Director of Nursing; Chief Nursing Officer; VP of Nursing",
    "Nurse Practitioner; Clinical Nurse Specialist; Physician Assistant; Midwife",
    "Healthcare Administrator; Medical Writer; Public Health Educator",
    "Khan Academy Nursing; NCSBN Learning Extension; Nurse.org Resources",
    "Saunders NCLEX Review; Mosby's Textbook for Nursing; Brunner & Suddarth's",
    "Lippincott NursingCenter; ATI Nursing Education; NCLEX Review Apps",
    "Brunners and Suddarth's Textbook of Medical-Surgical Nursing; Potter & Perry's Fundamentals of Nursing",
    "ANA.org; NCSBN.org; AACN.org",
    "Coursera Nursing Courses; Khan Academy NCLEX Prep; ATI Review",
    "NCLEX Practice Tests; Nursing.com; ATI SmartPrep",
    "National Student Nurses Association competitions; Sigma Theta Tau Honor Society",
    "American Nurses Association (ANA); AACN; Sigma Theta Tau International",
    "BSN; ADN; MSN",
    "Johns Hopkins School of Nursing; Duke University; University of Pennsylvania; AIIMS; CMC Vellore; Emory University",
    "FAFSA Nursing Scholarships; AACN Scholarships; Johnson & Johnson Nursing Scholarships",
    "Nursing school clinical rotations; Hospital internships; Community health placements",
    "Nursing research; Evidence-based practice studies; NIH Nursing Research",
    "Compassionate; Resilient; Attentive; Organized; Adaptable; Detail-oriented",
    "Nursing; Patient care; Health sciences; Medicine",
    "Moderate", "Low", "High", "Moderate"
])

CAREERS_9_20.append([
    "Nurse Practitioner", "Nursing", "Healthcare",
    "NP; Advanced Practice Registered Nurse; APRN; Nurse Clinician",
    "Nurse practitioners are advanced practice registered nurses who provide primary, specialty, and acute healthcare with a high degree of autonomy.",
    "NPs complete advanced education and clinical training enabling them to diagnose and treat illnesses, order tests, prescribe medications, and manage patient care independently or in collaboration with physicians. They serve as primary care providers in many settings.",
    "Conduct comprehensive patient assessments; Diagnose and manage acute and chronic conditions; Prescribe medications and treatments; Order and interpret diagnostic tests; Provide health education and counseling; Manage a patient panel independently",
    "Managing primary care patient panels; Developing chronic disease management programs; Implementing community health initiatives; Leading patient education workshops; Participating in telehealth expansion programs",
    "Primary care clinics; Hospitals; Specialty practices; Urgent care centers; Community health centers; Telehealth",
    "36-48", "None", "Moderate", "Good",
    "Master of Science in Nursing (MSN) or Doctor of Nursing Practice (DNP)",
    "MSN; DNP", "Advanced Nursing Practice; Nursing",
    "Biology; Chemistry; Anatomy; Physiology; Pharmacology; Mathematics",
    "NCLEX-RN; ANCC NP Certification; AANP Certification",
    "APRN License; National Board Certification as NP (FNP-BC; AGPCNP-BC; etc.)",
    "BLS; ACLS; PALS; NP Certification; DEA Registration",
    "Advanced health assessment; Differential diagnosis; Pharmacology; Pathophysiology; Clinical reasoning; Patient management",
    "Critical thinking; Communication; Autonomy; Empathy; Leadership; Collaboration",
    "Telehealth practice; Quality improvement; Research methodology; Clinical education; Healthcare informatics",
    "Stethoscope; Otoscope; Ophthalmoscope; Reflex hammer; Nebulizer; Spirometer",
    "Electronic Health Records (Epic/Cerner); Prescribing software; Telehealth platforms; Clinical decision support tools",
    "NULL", "Very High", "40% (Much faster than average)", "No", "Low",
    "Primary care clinics; Hospitals; Specialty practices; Urgent care; Telehealth; Academic institutions",
    "Kaiser Permanente; HCA Healthcare; Mayo Clinic; Cleveland Clinic; CVS MinuteClinic",
    "115000", "130000", "145000", "170000", "USD",
    "Nurse Practitioner; Junior NP", "Experienced NP; Specialty NP",
    "Senior NP; Lead NP",
    "Chief NP; Director of Advanced Practice; Clinical Director",
    "Physician Assistant; Clinical Nurse Specialist; Certified Nurse Midwife; Physician",
    "Healthcare Administrator; Clinical Educator; Medical Writer",
    "AANP Resources; ANCC Certification Info; NP Student Blog",
    "Advanced Health Assessment; Varcarolis' Foundations of Psychiatric-Mental Health Nursing; NP Review Books",
    "AANP.org; ANCC.org; NPinfo.org",
    "AANP National Conference; ANCC Certification Prep; Coursera NP Courses",
    "NP Board Review Questions; NP Prep App; UWorld NP",
    "American Association of Nurse Practitioners (AANP); ANCC; National Association of Pediatric Nurse Practitioners",
    "MSN; DNP",
    "University of Pennsylvania; Johns Hopkins; Emory; UCSF; Duke University; Case Western",
    "AANP Scholarships; ANCC Scholarships; HRSA Nursing Scholarships",
    "NP clinical rotations; Primary care practicums; Specialty clinical experiences",
    "Nurse practitioner research; AANP research initiatives; HRSA research grants",
    "Independent; Analytical; Compassionate; Decisive; Confident; Adaptable",
    "Primary care; Nursing; Medicine; Patient advocacy; Health promotion",
    "Moderate", "Moderate", "High", "Moderate"
])

CAREERS_9_20.append([
    "Clinical Nurse Specialist", "Nursing", "Healthcare",
    "CNS; Advanced Practice Nurse; Clinical Specialist; Nurse Expert",
    "A clinical nurse specialist is an advanced practice nurse who serves as an expert clinician, educator, researcher, and consultant in a specialized area of nursing.",
    "CNSs provide expert clinical care in a specialized area, influence nursing practice standards, serve as patient care advocates, and lead quality improvement initiatives. They bridge the gap between research and clinical practice, mentoring staff nurses and improving patient outcomes.",
    "Provide expert clinical consultation; Lead evidence-based practice initiatives; Mentor and educate nursing staff; Conduct quality improvement projects; Develop nursing protocols and policies; Analyze patient outcomes data",
    "Leading evidence-based practice transformations; Implementing new nursing protocols; Conducting staff education programs; Managing specialty patient care initiatives; Researching nursing outcomes",
    "Hospitals; Specialty care units; Long-term care facilities; Academic institutions; Community health organizations",
    "40-48", "None", "Moderate", "Good",
    "Master of Science in Nursing (MSN) or Doctor of Nursing Practice (DNP)",
    "MSN; DNP", "Clinical Nurse Specialty; Advanced Nursing Practice",
    "Biology; Anatomy; Physiology; Pharmacology; Nursing Theory; Research Methods",
    "NCLEX-RN; ANCC CNS Certification",
    "APRN License; ANCC CNS Certification in Specialty",
    "BLS; ACLS; PALS; Specialty Certification; Evidence-Based Practice Training",
    "Advanced clinical assessment; Evidence-based practice; Quality improvement; Patient safety; Staff education; Clinical research",
    "Leadership; Mentoring; Communication; Analytical thinking; Advocacy; Collaboration",
    "Nursing informatics; Healthcare quality; Patient safety science; Research methodology",
    "Clinical practice guidelines databases; Quality improvement tools; EHR systems; Patient outcome tracking software",
    "Evidence-based practice databases (CINAHL; PubMed); EHR analytics tools; Statistical software (SPSS)",
    "NULL", "High", "5% (As fast as average)", "No", "Low",
    "Hospitals; Academic medical centers; Specialty clinics; Long-term care facilities; Nursing schools",
    "Cleveland Clinic; Mayo Clinic; Johns Hopkins Nursing; Duke University Hospital; Mass General",
    "100000", "115000", "135000", "155000", "USD",
    "Clinical Nurse Specialist (Entry)", "Senior Clinical Nurse Specialist",
    "Lead Clinical Nurse Specialist",
    "Director of Clinical Nurse Specialists; VP of Nursing Practice",
    "Nurse Practitioner; Clinical Educator; Nurse Manager; Quality Director",
    "Nursing Educator; Healthcare Consultant; Quality Improvement Specialist",
    "AACN Resources; ANCC Certification Guide; ONS Resources",
    "Clinical Nursing Research; Evidence-Based Nursing Practice; Hamric's Advanced Practice Nursing",
    "AACN.org; ONS.org; ANCC.org; NACNS.org",
    "AACN NTI Conference; ANCC Certification Courses; ONS Congress",
    "Evidence-Based Practice Appraisal Tools; Quality Improvement Simulators",
    "American Association of Critical-Care Nurses (AACN); Oncology Nursing Society (ONS); NACNS",
    "MSN; DNP",
    "University of Pennsylvania; Johns Hopkins; Emory; UCSF; University of Michigan; Vanderbilt",
    "AACN Scholarships; ONS Foundation Scholarships",
    "CNS clinical practicums; Specialty rotations; Leadership experiences",
    "ONS Research; AACN Research Grants; NIH Nursing Research",
    "Analytical; Mentoring; Detail-oriented; Evidence-based; Collaborative; Leader",
    "Nursing practice; Evidence-based medicine; Education; Research; Quality improvement",
    "Moderate", "Moderate", "High", "High"
])

CAREERS_9_20.append([
    "Nurse Anesthetist (CRNA)", "Nursing", "Healthcare",
    "CRNA; Certified Registered Nurse Anesthetist; Nurse Anesthesiologist",
    "Certified registered nurse anesthetists are advanced practice nurses who administer anesthesia and provide anesthesia-related care.",
    "CRNAs provide anesthesia services independently or in collaboration with anesthesiologists. They perform pre-anesthetic assessments, develop anesthesia plans, administer general, regional, and MAC anesthesia, monitor patients during procedures, and manage post-anesthesia care.",
    "Perform pre-anesthetic patient evaluations; Administer general and regional anesthesia; Monitor patient vital signs during procedures; Manage airway emergencies; Provide post-anesthesia recovery care; Manage chronic pain patients",
    "Managing anesthesia services in rural hospitals; Implementing enhanced recovery after surgery protocols; Leading anesthesia quality improvement; Providing obstetric anesthesia; Conducting anesthesia research",
    "Hospitals; Surgical centers; Obstetric units; Pain management clinics; Military medical facilities; Rural healthcare facilities",
    "40-60", "Low", "Moderate", "Fair",
    "Doctor of Nursing Practice (DNP) in Nurse Anesthesia",
    "DNP; MSN", "Nurse Anesthesia; Advanced Nursing Practice",
    "Biology; Chemistry; Physics; Anatomy; Physiology; Pharmacology",
    "NCLEX-RN; NBCRNA Certification Exam (NCE)",
    "APRN License; CRNA Certification (NBCRNA); BLS; ACLS",
    "CRNA Board Certification; Pain Management Certification; ACLS; PALS",
    "Anesthesia administration; Airway management; Regional anesthesia; Hemodynamic monitoring; Pharmacology; Critical care medicine",
    "Calm under pressure; Quick decision-making; Attention to detail; Teamwork; Manual dexterity; Resilience",
    "Pain medicine; Critical care; Cardiac anesthesia; Research; Education",
    "Anesthesia machine; Laryngoscope; Video laryngoscope; Ultrasound; Syringe driver; Nerve block kit",
    "Anesthesia information management systems; Dosing calculators; Vital sign monitors; Epic/Cerner",
    "NULL", "Very High", "40% (Much faster than average)", "No", "Moderate",
    "Hospitals; Surgical centers; Pain clinics; Rural health facilities; Military",
    "CRNA practice groups; HCA Healthcare; Mayo Clinic; VA Hospitals; NorthStar Anesthesia",
    "200000", "220000", "250000", "300000", "USD",
    "New Graduate CRNA", "Experienced CRNA", "Senior CRNA",
    "Chief CRNA; Director of Nurse Anesthesia",
    "Anesthesiologist; Physician Assistant; Nurse Practitioner; Pain Management Specialist",
    "Critical Care Nurse; Nurse Educator; Healthcare Administrator",
    "AANA Resources; NBCRNA Certification Guide; CRNA School Info",
    "Nagelhout's Nurse Anesthesia; Basics of Anesthesia; Clinical Anesthesia Procedures",
    "AANA.com; NBCRNA.org; ANA.org",
    "AANA Annual Meeting; NBCRNA Certification Prep; Anesthesia Education Seminars",
    "CRNA Board Review Questions; Anesthesia Simulation Apps",
    "American Association of Nurse Anesthetists (AANA); ASA; International Federation of Nurse Anesthetists",
    "DNP; MSN",
    "University of Pittsburgh; Duke; MUSC; UCSF; Rush University; Uniformed Services University",
    "AANA Foundation Scholarships; HRSA Scholarships",
    "CRNA clinical rotations; Anesthesia practicums; Fellowship experiences",
    "AANA Research Grants; Anesthesia Patient Safety Foundation Research",
    "Calm; Precise; Decisive; Vigilant; Resilient; Meticulous",
    "Anesthesia; Critical care; Pharmacology; Patient safety; Surgery",
    "Moderate", "Moderate", "High", "Moderate"
])

CAREERS_9_20.append([
    "Nurse Midwife", "Nursing", "Healthcare",
    "CNM; Certified Nurse Midwife; Midwife; APRN Midwife",
    "Certified nurse-midwives provide comprehensive reproductive and primary healthcare to women with emphasis on childbirth.",
    "CNMs provide prenatal care, manage labor and delivery, provide postpartum care, and offer gynecological services. They emphasize natural physiologic processes, low-intervention approaches, and patient education while managing complications and collaborating with physicians.",
    "Provide prenatal care and education; Manage labor and delivery; Provide postpartum care for mother and baby; Perform gynecological exams; Prescribe contraceptives; Offer newborn care assessments",
    "Managing birth center operations; Implementing low-intervention birth programs; Developing women's health education initiatives; Conducting midwifery research; Leading community prenatal outreach programs",
    "Birth centers; Hospitals; Outpatient clinics; Home birth practices; Community health centers; Private practices",
    "40-48", "None", "Moderate", "Good",
    "Master of Science in Nursing (MSN) or Doctor of Nursing Practice (DNP) in Nurse-Midwifery",
    "MSN; DNP", "Nurse-Midwifery; Advanced Nursing Practice",
    "Biology; Chemistry; Anatomy; Physiology; Pharmacology; Psychology",
    "NCLEX-RN; AMCB Certification Exam",
    "APRN License; AMCB Certification (CNM); BLS",
    "AMCB Board Certification; NRP (Neonatal Resuscitation); ACLS; Fetal Heart Monitoring Certification",
    "Labor management; Prenatal assessment; Newborn assessment; GYN examination; Pharmacology for women; Breastfeeding support",
    "Empathy; Calm presence; Communication; Patience; Advocacy; Cultural sensitivity",
    "Lactation consulting; Holistic birth practices; Community health; Birth education classes",
    "Fetal heart monitor; Doppler; Non-stress test equipment; Birth stool; Birthing tub; Newborn resuscitation equipment",
    "Electronic Health Records; Fetal monitoring systems; Prenatal care software",
    "NULL", "Very High", "11% (Much faster than average)", "No", "Low",
    "Birth centers; Hospitals; Outpatient clinics; Home birth practices; Community organizations",
    "CNM practice groups; HCA Healthcare; Community birth centers; Planned Parenthood; VA Hospitals",
    "110000", "125000", "145000", "170000", "USD",
    "Staff CNM", "Senior CNM", "Lead CNM",
    "Director of Midwifery; Chief Midwife",
    "Obstetrician-Gynecologist; Nurse Practitioner; Lactation Consultant; Doula",
    "Women's Health Nurse Practitioner; Clinical Educator; Public Health Nurse",
    "Midwifery Today; AABC Resources; Ina May's Guide to Childbearing",
    "Lowdermilk's Maternity Nursing; Midwifery Textbook",
    "AABC.org; AMCB.org; ACNM.org",
    "ACNM Annual Meeting; Midwifery Bundle of Skills; AMCB Review Course",
    "Midwifery Skills Simulator; Labor Management Case Studies",
    "American College of Nurse-Midwives (ACNM); American Midwifery Certification Board (AMCB)",
    "MSN; DNP",
    "Vanderbilt; Georgetown; NYU; Frontier Nursing University; Emory; University of Michigan",
    "ACNM Scholarships; Frontier Nursing University Scholarships; HRSA",
    "Midwifery clinical rotations; Birth center practicums; Community health placements",
    "ACNM Research; Midwifery research grants; NIH maternal health research",
    "Compassionate; Calm; Patient; Nurturing; Decisive; Adaptable",
    "Midwifery; Women's health; Childbirth; Natural processes; Patient advocacy",
    "High", "Low", "High", "Moderate"
])

CAREERS_9_20.append([
    "Pediatric Nurse", "Nursing", "Healthcare",
    "Pediatric RN; Children's Nurse; Child Health Nurse; Peds Nurse",
    "Pediatric nurses specialize in providing healthcare to infants, children, and adolescents in various clinical settings.",
    "Pediatric nurses assess and manage the health needs of children from birth through adolescence. They administer medications, perform developmental screenings, provide family education, and work closely with pediatricians and child specialists.",
    "Assess pediatric patient conditions; Administer age-appropriate medications; Monitor growth and development; Educate families on child health; Provide emotional support to young patients; Coordinate care with pediatric specialists",
    "Implementing pediatric pain management protocols; Developing child life programs; Leading immunization campaigns; Conducting developmental screening initiatives; Managing pediatric chronic illness programs",
    "Children's hospitals; Pediatric clinics; School health offices; Pediatric emergency departments; Community health centers",
    "36-48", "None", "Moderate", "Good",
    "Bachelor of Science in Nursing (BSN)",
    "BSN; MSN", "Pediatric Nursing; Nursing",
    "Biology; Anatomy; Physiology; Child Development; Psychology; Mathematics",
    "NCLEX-RN; CPN (Certified Pediatric Nurse)",
    "Registered Nurse License; CPN Certification; BLS; PALS",
    "CPN Certification; PALS; Pediatric Nursing Certification",
    "Pediatric assessment; Growth and development monitoring; Medication dosing for children; Child communication; Family education; Pediatric emergency care",
    "Patience; Communication with children; Empathy; Adaptability; Attention to detail; Family-centered care",
    "Pediatric advanced practice; Neonatal care; School nursing; Pediatric oncology nursing; Research",
    "Pediatric vital sign equipment; Growth charts; Pediatric IV equipment; Child-friendly medical tools",
    "Pediatric EHR modules; Growth tracking software; Immunization tracking; Developmental screening tools",
    "NULL", "Very High", "6% (Faster than average)", "No", "Low",
    "Children's hospitals; Pediatric clinics; School districts; Community health centers; Home health agencies",
    "Children's Hospital of Philadelphia; Boston Children's Hospital; Cincinnati Children's; St. Jude; Texas Children's Hospital",
    "65000", "80000", "100000", "130000", "USD",
    "Pediatric Staff Nurse", "Senior Pediatric Nurse", "Pediatric Charge Nurse",
    "Pediatric Nurse Manager; Director of Pediatric Nursing",
    "Nurse Practitioner (Pediatric); Pediatric Clinical Nurse Specialist; Child Life Specialist",
    "Neonatal Nurse; School Nurse; Pediatric Emergency Nurse",
    "Pediatric Nursing Textbook; Wong's Nursing Care of Infants and Children; NAPNAP Resources",
    "Pediatric Nursing: The Critical Components of Nursing Care; Hockenberry Wong's Pediatric Nursing",
    "PNA.org; NAPNAP.org; AAP.org",
    "PNA Annual Conference; NAPNAP Certification Prep; Pediatric Nursing Review Courses",
    "Pediatric Assessment Simulators; Growth and Development Apps",
    "Pediatric Nursing Certification Board (PNCB); NAPNAP; AAP",
    "BSN; MSN",
    "Johns Hopkins; University of Pennsylvania; Emory; University of Michigan; Vanderbilt; Children's Hospital programs",
    "PNA Scholarships; NAPNAP Scholarships; Pediatric Nursing Grants",
    "Pediatric clinical rotations; Children's hospital externships; School nurse practicums",
    "Pediatric nursing research; NIH child health research; PNA research initiatives",
    "Compassionate; Patient; Playful; Detail-oriented; Resilient; Nurturing",
    "Pediatrics; Child development; Nursing; Family health; Patient care",
    "Moderate", "Low", "High", "Moderate"
])

CAREERS_9_20.append([
    "Emergency Room Nurse", "Nursing", "Healthcare",
    "ER Nurse; Emergency Nurse; Emergency Department Nurse; Trauma Nurse",
    "Emergency room nurses provide critical care to patients with urgent and life-threatening medical conditions in fast-paced emergency departments.",
    "ER nurses triage and treat patients with acute illnesses and injuries. They rapidly assess patient conditions, prioritize treatments, manage multiple simultaneous patients, and work effectively in high-stress environments alongside emergency physicians and trauma teams.",
    "Triage incoming patients; Administer emergency medications and treatments; Perform wound care and suturing; Monitor critically ill patients; Manage trauma resuscitation; Coordinate patient transfers and admissions",
    "Implementing triage protocols; Managing mass casualty preparedness; Developing emergency department flow improvements; Leading resuscitation teams; Conducting emergency medicine research",
    "Hospital emergency departments; Trauma centers; Urgent care facilities; Critical access hospitals; Military medical facilities",
    "36-48", "None", "Moderate", "Poor",
    "Bachelor of Science in Nursing (BSN)",
    "BSN; MSN", "Emergency Nursing; Nursing",
    "Biology; Anatomy; Physiology; Pharmacology; Trauma Science; Mathematics",
    "NCLEX-RN; CEN (Certified Emergency Nurse)",
    "Registered Nurse License; CEN Certification; BLS; ACLS; TNCC",
    "CEN Certification; TNCC; ACLS; PALS; Trauma Nursing Core Course",
    "Triage assessment; Emergency medication administration; Cardiac monitoring; Trauma care; Wound management; Airway management",
    "Quick thinking; Multitasking; Calm under pressure; Communication; Resilience; Teamwork",
    "Trauma nursing; Critical care; Pediatric emergency; Forensic nursing; Flight nursing",
    "Cardiac monitor; Defibrillator; IV pumps; Intubation supplies; Wound care supplies; Point-of-care testing devices",
    "Emergency Department EHR; Triage systems; Patient tracking boards; Trauma documentation tools",
    "NULL", "Very High", "6% (Faster than average)", "No", "Moderate",
    "Hospital emergency departments; Trauma centers; Urgent care; Freestanding EDs",
    "HCA Healthcare; Tenet Healthcare; Kaiser Permanente; Mayo Clinic; Cedars-Sinai",
    "70000", "85000", "100000", "125000", "USD",
    "Emergency Room Nurse", "Senior ER Nurse", "Trauma Nurse Specialist",
    "Nurse Manager ER; Director of Emergency Nursing",
    "Flight Nurse; Critical Care Nurse; Trauma Nurse Specialist",
    "ICU Nurse; Urgent Care Nurse; School Nurse",
    "ENA Resources; Emergency Nursing Core Curriculum; Jones & Bartlett Emergency Nursing",
    "Emergency Nursing: The Core Curriculum; Sheehy's Manual of Emergency Nursing",
    "ENA.org; CEN.org; ENA Learning Center",
    "ENA Annual Conference; CEN Certification Prep; Emergency Nursing Review Courses",
    "Emergency Triage Simulator; Trauma Assessment Apps",
    "Emergency Nurses Association (ENA); American College of Emergency Physicians (ACEP)",
    "BSN; MSN",
    "Johns Hopkins; University of Maryland; Duke; Emory; University of Pennsylvania; Wayne State",
    "ENA Scholarships; Emergency Nursing Research Grants",
    "ED clinical rotations; Trauma center externships; Emergency nursing practicums",
    "ENA Research Foundation; NIH Emergency Medicine Research; ACEP Research",
    "Quick-thinking; Resilient; Calm; Adaptable; Decisive; Empathetic",
    "Emergency medicine; Trauma care; Critical care; High-pressure environments",
    "Moderate", "Moderate", "High", "High"
])

CAREERS_9_20.append([
    "Dentist", "Dental", "Healthcare",
    "Dental Doctor; General Dentist; DDS; DMD",
    "Dentists diagnose and treat problems with patients' teeth, gums, and related parts of the mouth.",
    "Dentists provide preventive and restorative dental care including examinations, cleanings, fillings, extractions, and cosmetic procedures. They interpret X-rays, develop treatment plans, educate patients on oral hygiene, and manage dental practice operations.",
    "Perform dental examinations; Diagnose oral diseases; Create treatment plans; Perform dental procedures (fillings; crowns; extractions); Take and interpret dental X-rays; Educate patients on oral hygiene",
    "Managing dental practice operations; Implementing preventive care programs; Developing cosmetic dentistry services; Leading community oral health initiatives; Conducting dental research",
    "Dental offices; Dental clinics; Hospitals; Community health centers; Academic institutions",
    "36-44", "None", "Moderate", "Good",
    "Doctor of Dental Surgery (DDS) or Doctor of Medicine in Dentistry (DMD)",
    "DDS; DMD", "Dentistry; Dental Surgery",
    "Biology; Chemistry; Physics; Mathematics; English; Art (helpful)",
    "DAT (Dental Admission Test); NBDE Parts I and II; NEET BDS (India)",
    "State Dental License; DEA Registration",
    "Board Certification in General Dentistry (ABGD); BLS; ACLS",
    "Dental examination; Cavity preparation; Crown and bridge work; Root canal therapy; Periodontal treatment; Dental implant placement",
    "Manual dexterity; Attention to detail; Patient communication; Practice management; Hand-eye coordination",
    "Cosmetic dentistry; Implantology; Sedation dentistry; Dental photography; Digital dentistry",
    "Dental chair; Dental drill; Dental X-ray machine; Impression materials; Curing light; Dental instruments",
    "Dental practice management software (Dentrix; Eaglesoft); Digital X-ray imaging; CAD/CAM systems (CEREC)",
    "NULL", "High", "4% (As fast as average)", "No", "Low",
    "Dental offices; Hospitals; Community health centers; Academic institutions; Military",
    "Aspen Dental; Heartland Dental; Pacific Dental Services; Individual private practices",
    "160000", "190000", "220000", "300000", "USD",
    "Associate Dentist", "Associate Dentist (Experienced)", "Practice Owner Dentist",
    "Dental Director; Chief of Dental Services",
    "Orthodontist; Oral Surgeon; Periodontist; Endodontist",
    "Dental Hygienist; Dental Assistant; Prosthodontist; Public Health Dentist",
    "ADA Patient Resources; Khan Academy Dental; BLS Dental Career Info",
    "Sturdevant's Art and Science of Operative Dentistry; Oral and Maxillofacial Surgery",
    "ADA.org; ADEA.org; AGD.org",
    "ADA Annual Meeting; ADEA Sessions; Dental board prep courses",
    "Dental Simulator Software; Virtual Reality Dental Training",
    "American Dental Association (ADA); American Dental Education Association (ADEA); Academy of General Dentistry (AGD)",
    "DDS; DMD",
    "Harvard School of Dental Medicine; UCSF; University of Michigan; Columbia; AIIMS Dental; Maulana Azad Institute",
    "ADA Foundation Scholarships; ADEA Scholarships; Colgate-Palmolive Scholarships",
    "Dental school clinical rotations; Community dental clinics; Externships",
    "ADA Research; NIH Craniofacial Research; Dental clinical trials",
    "Detail-oriented; Manual dexterity; Patient; Artistic; Business-minded; Caring",
    "Dentistry; Oral health; Patient care; Art; Science",
    "High", "Low", "High", "Moderate"
])

CAREERS_9_20.append([
    "Orthodontist", "Dental", "Healthcare",
    "Orthodontic Specialist; Braces Doctor; Orthodontic Dentist",
    "Orthodontists specialize in diagnosing, preventing, and correcting misaligned teeth and jaws.",
    "Orthodontists evaluate patients for malocclusion, design and apply braces and aligners and other orthodontic appliances, monitor treatment progress, and collaborate with general dentists. They use advanced imaging and planning software for comprehensive treatment plans.",
    "Conduct orthodontic examinations; Diagnose malocclusion and jaw discrepancies; Design treatment plans; Apply and adjust braces and aligners; Monitor treatment progress; Perform retention management",
    "Implementing digital orthodontic planning; Managing complex orthodontic-surgical cases; Conducting research on orthodontic outcomes; Developing accelerated treatment protocols; Training orthodontic residents",
    "Orthodontic offices; Dental practices; Academic institutions; Hospital dental departments",
    "36-44", "None", "Moderate", "Good",
    "DDS or DMD plus 2-3 year Orthodontic Residency",
    "DDS; DMD; MS in Orthodontics", "Orthodontics; Dentistry",
    "Biology; Chemistry; Physics; Mathematics; Art; English",
    "DAT; NBDE; Orthodontic Residency Match",
    "State Dental License; Board Certification in Orthodontics",
    "American Board of Orthodontics (ABO) Certification; BLS",
    "Orthodontic diagnosis; Treatment planning; Appliance adjustment; Cephalometric analysis; Digital treatment planning; Retention management",
    "Manual dexterity; Spatial visualization; Attention to detail; Patient communication; Patience; Artistic eye",
    "Digital orthodontics; 3D printing; Aligner therapy; TMJ treatment; Surgical orthodontics",
    "Orthodontic pliers; Wire benders; Bracket placement instruments; Cephalometric analysis tools; 3D scanners",
    "OrthoCad; Dolphin Imaging; 3Shape; Invisalign ClinCheck; Digital treatment planning software",
    "NULL", "High", "4% (As fast as average)", "No", "Low",
    "Orthodontic offices; Academic institutions; Group practices",
    "Aspen Dental Orthodontics; Kool Smiles; Private orthodontic practices; Academic orthodontic departments",
    "200000", "280000", "350000", "500000", "USD",
    "Orthodontic Resident", "Associate Orthodontist", "Senior Orthodontist",
    "Practice Owner; Department Chair",
    "Pediatric Dentist; Oral Surgeon; Prosthodontist; TMJ Specialist",
    "General Dentist; Dental Surgeon; Dental Educator",
    "AAO Patient Resources; Orthodontic Board Review; Orthodontics Today",
    "Graber's Orthodontics: Current Principles and Techniques; Contemporary Orthodontics",
    "AAO.org; ABO.org; Orthodontics.org",
    "AAO Annual Meeting; ABO Certification Course; Orthodontic Residency Programs",
    "Virtual Orthodontic Treatment Planning; Aligner Design Software",
    "American Association of Orthodontists (AAO); American Board of Orthodontics (ABO); World Federation of Orthodontists",
    "DDS; DMD; MS Orthodontics",
    "Harvard; UCSF; University of Michigan; Columbia; University of the Pacific; AIIMS",
    "AAO Foundation Scholarships; ADEA Scholarships",
    "Orthodontic residency rotations; Clinical externships",
    "AAO Research; Orthodontic clinical trials; NIH Craniofacial Research",
    "Artistic; Detail-oriented; Patient; Precise; Visual; Communicative",
    "Orthodontics; Aesthetics; Dentistry; Biomechanics; Patient care",
    "High", "Moderate", "High", "Moderate"
])

CAREERS_9_20.append([
    "Oral and Maxillofacial Surgeon", "Dental", "Healthcare",
    "Oral Surgeon; Maxillofacial Surgeon; OMFS; Dental Surgeon",
    "Oral and maxillofacial surgeons perform surgical procedures on the face, mouth, jaws, and associated structures.",
    "OMFS specialists perform complex extractions including wisdom teeth, dental implant placement, corrective jaw surgery, treatment of facial trauma, and reconstructive surgery. They are dual-trained in dentistry and medicine and manage patients under general anesthesia.",
    "Perform complex dental extractions; Place dental implants; Correct jaw deformities; Treat facial trauma; Manage facial infections; Administer general anesthesia",
    "Managing complex facial trauma cases; Performing orthognathic surgery; Conducting dental implant research; Implementing facial reconstruction programs; Training surgical residents",
    "Hospitals; Surgical centers; Oral surgery practices; Academic medical centers; Trauma centers",
    "40-50", "Low", "Moderate", "Fair",
    "DDS or DMD plus 4-6 year Oral Surgery Residency; MD (for some programs)",
    "DDS; DMD; MD; OMFS Residency Certificate", "Oral and Maxillofacial Surgery; Dentistry; Medicine",
    "Biology; Chemistry; Physics; Anatomy; Surgery; English",
    "DAT; NBDE; Medical Boards (for dual degree programs)",
    "State Dental License; Board Certification in OMFS (ABOMS); Medical License (if dual degree)",
    "ABOMS Certification; ATLS; ACLS; BLS",
    "Facial anatomy knowledge; Surgical technique; Anesthesia administration; Implant surgery; Trauma management; Facial reconstruction",
    "Manual dexterity; Decisiveness; Calm under pressure; Attention to detail; Communication; Stamina",
    "Dental implant systems; Orthognathic surgery planning; Facial trauma repair; Microsurgery; TMJ surgery",
    "Surgical instruments; Dental implant drills; Orthognathic plates and screws; 3D surgical planning software",
    "3D imaging software; Surgical navigation systems; Implant planning software; Epic/Cerner",
    "NULL", "High", "3% (Slower than average)", "No", "Moderate",
    "Hospitals; Oral surgery practices; Trauma centers; Academic medical centers; Military",
    "Private OMFS practices; Hospital-based oral surgery; Academic oral surgery departments; Military",
    "300000", "380000", "450000", "600000", "USD",
    "Oral Surgery Resident", "Staff Oral Surgeon", "Senior Oral Surgeon",
    "Chief of Oral Surgery; Department Chair",
    "Maxillofacial Prosthodontist; TMJ Specialist; Facial Plastic Surgeon",
    "Periodontist; Endodontist; Plastic Surgeon",
    "AAOMS Patient Resources; OMFS Board Review; Peterson's Principles of OMFS",
    "Modern Oral and Maxillofacial Surgery; Contemporary Oral and Maxillofacial Surgery",
    "AAOMS.org; ABOMS.org",
    "AAOMS Annual Meeting; OMFS Board Prep Courses; Advanced Surgical Training",
    "Surgical Simulation Software; Virtual Surgical Planning",
    "American Association of Oral and Maxillofacial Surgeons (AAOMS); American Board of OMFS (ABOMS)",
    "DDS; DMD; OMFS Residency",
    "Harvard; University of Michigan; UCSF; Columbia; UPenn; University of Washington",
    "AAOMS Foundation Scholarships",
    "Oral surgery clinical rotations; Hospital-based OMFS rotations",
    "AAOMS Research; NIH Craniofacial Research; Implant research",
    "Decisive; Precise; Confident; Detail-oriented; Resilient; Manual dexterity",
    "Surgery; Oral health; Facial anatomy; Trauma care; Implants",
    "Moderate", "Moderate", "High", "High"
])

CAREERS_9_20.append([
    "Dental Hygienist", "Dental", "Healthcare",
    "Hygienist; Dental Hygiene Specialist; Oral Hygienist; RDH",
    "Dental hygienists clean teeth, examine patients for signs of oral disease, and provide preventive dental care.",
    "Dental hygienists perform professional teeth cleanings, take and develop dental X-rays, apply fluoride treatments and sealants, educate patients on oral hygiene, and assist dentists during procedures. They are essential preventive care providers.",
    "Perform dental cleanings and scaling; Take dental X-rays; Apply fluoride treatments and sealants; Screen for oral cancer; Educate patients on oral hygiene; Record patient medical and dental histories",
    "Implementing preventive oral health programs; Conducting community dental health screenings; Developing patient education materials; Participating in public health dental programs; Advancing dental hygiene practice",
    "Dental offices; Dental clinics; Public health clinics; Schools; Community health centers",
    "36-40", "None", "Low", "Good",
    "Associate Degree in Dental Hygiene (minimum); Bachelor's preferred",
    "AS; BS; BAS", "Dental Hygiene",
    "Biology; Chemistry; Anatomy; Physiology; English; Health Sciences",
    "Dental Hygiene National Board Examination (NBDHE); Regional Clinical Exams",
    "State Dental Hygiene License; Local Anesthesia Permit (varies by state)",
    "Certified Dental Hygienist; Local Anesthesia Certification; Nitrous Oxide Certification",
    "Dental scaling and root planing; Dental radiography; Fluoride application; Oral cancer screening; Patient education; Infection control",
    "Attention to detail; Communication; Manual dexterity; Patient education skills; Empathy; Organization",
    "Public health dental hygiene; Dental photography; Laser therapy; Periodontal therapy; Dental education",
    "Dental chair; Scaler (ultrasonic and hand); Dental X-ray unit; Fluoride trays; Dental explorer; Periodontal probe",
    "Dental practice management software (Dentrix; Eaglesoft); Digital X-ray imaging; Patient education software",
    "NULL", "High", "9% (Much faster than average)", "No", "Low",
    "Dental offices; Public health clinics; Schools; Community health centers; Corporate dental practices",
    "Aspen Dental; Heartland Dental; Pacific Dental Services; Community health centers; School-based programs",
    "42000", "55000", "70000", "85000", "USD",
    "Staff Dental Hygienist", "Senior Dental Hygienist", "Lead Dental Hygienist",
    "Dental Hygiene Program Director; Public Health Dental Hygiene Supervisor",
    "Dental Therapist; Dental Assistant; Public Health Educator; Periodontal Therapist",
    "Dental Office Manager; Public Health Coordinator; Dental Educator",
    "ADHA Resources; BLS Dental Hygienist Info; Dental Hygiene Today",
    "Dental Hygiene: Clinical Practice; Darby's Comprehensive Review of Dental Hygiene; NBDHE Review",
    "ADHA.org; NDHBA.org; ADEA.org",
    "ADHA Annual Conference; NBDHE Board Prep; Continuing Education Courses",
    "NBDHE Practice Exams; Dental Hygiene Simulation Software",
    "American Dental Hygienists' Association (ADHA); American Dental Education Association (ADEA)",
    "AS; BS; BAS",
    "University of Michigan; University of Minnesota; UNC Chapel Hill; Indiana University; University of Texas Health",
    "ADHA Foundation Scholarships; Colgate Scholarships; dental hygiene program grants",
    "Dental hygiene clinical rotations; Community health clinics; Externships",
    "Dental hygiene research; Public health oral care studies; NIH oral health research",
    "Detail-oriented; Caring; Communicative; Organized; Patient; Manual dexterity",
    "Dental hygiene; Oral health; Preventive care; Patient education",
    "Moderate", "Low", "High", "Low"
])

CAREERS_9_20.append([
    "Prosthodontist", "Dental", "Healthcare",
    "Prosthodontic Specialist; Dental Prosthesis Doctor; Restorative Dentist",
    "Prosthodontists specialize in restoring and replacing missing teeth and oral structures with prosthetic devices.",
    "Prosthodontists design and fabricate dental prostheses including crowns, bridges, dentures, and dental implants. They manage complex restorative cases, collaborate with dental laboratories, and use advanced digital technology to restore oral function and aesthetics.",
    "Evaluate patients for prosthetic needs; Design and place crowns and bridges; Fabricate and adjust dentures; Manage dental implant restorations; Collaborate with dental labs; Perform cosmetic smile makeovers",
    "Managing full-mouth rehabilitation cases; Implementing digital dentistry workflows; Conducting prosthodontic research; Training dental residents; Developing aesthetic dental solutions",
    "Dental offices; Prosthodontic practices; Academic institutions; Hospital dental departments",
    "36-44", "None", "Moderate", "Good",
    "DDS or DMD plus 2-3 year Prosthodontic Residency",
    "DDS; DMD; MS in Prosthodontics", "Prosthodontics; Dentistry",
    "Biology; Chemistry; Physics; Art; English; Design",
    "DAT; NBDE; Prosthodontic Residency Match",
    "State Dental License; Board Certification in Prosthodontics",
    "American Board of Prosthodontics (ABP) Certification; BLS",
    "Fixed prosthodontics; Removable prosthodontics; Implant prosthodontics; Occlusion management; Dental materials science; Digital dentistry",
    "Artistic vision; Attention to detail; Manual dexterity; Patient communication; Spatial visualization; Precision",
    "Digital smile design; CAD/CAM dentistry; 3D printing in dentistry; Implant planning; Occlusal analysis",
    "Dental articulator; Shade guide; Dental laboratory equipment; CAD/CAM milling machines; 3D scanners",
    "Exocad; 3Shape; CEREC; Dental lab management software; Digital impression systems",
    "NULL", "High", "4% (As fast as average)", "No", "Low",
    "Prosthodontic practices; Dental laboratories; Academic institutions; Hospital dental departments",
    "Private prosthodontic practices; Academic prosthodontic departments; VA dental services",
    "170000", "220000", "280000", "350000", "USD",
    "Prosthodontic Resident", "Associate Prosthodontist", "Senior Prosthodontist",
    "Practice Owner; Program Director",
    "Maxillofacial Prosthodontist; Implantologist; Cosmetic Dentist",
    "General Dentist; Dental Laboratory Technician; Esthetic Dentist",
    "ACP Patient Resources; Prosthodontic Board Review; Digital Dentistry Today",
    "Fundamentals of Fixed Prosthodontics; McCracken's Removable Partial Prosthodontics",
    "ACP.org; ABP.org; PFA.org",
    "ACP Annual Meeting; Prosthodontic Board Prep; Digital Dentistry Workshops",
    "Virtual Articulator Software; Digital Smile Design Tools",
    "American College of Prosthodontists (ACP); American Board of Prosthodontics (ABP); Academy of Prosthodontics",
    "DDS; DMD; MS Prosthodontics",
    "Harvard; University of Michigan; UCSF; Columbia; NYU; University of Texas Health",
    "ACP Scholarships; ADEA Prosthodontic Awards",
    "Prosthodontic residency rotations; Dental laboratory externships",
    "ACP Research; Dental implant research; Digital dentistry studies",
    "Artistic; Precise; Detail-oriented; Patient; Visual; Creative",
    "Prosthodontics; Dentistry; Art; Aesthetics; Patient care",
    "High", "Low", "High", "Moderate"
])

print(f"CAREERS_9_20 count: {len(CAREERS_9_20)}")
