"""initial_schema

Revision ID: 21039be197ed
Revises: 
Create Date: 2026-07-21 23:15:16.798719
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '21039be197ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('average_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('growth_outlook', sa.String(length=100), nullable=True),
    sa.Column('demand_level', sa.String(length=50), nullable=True),
    sa.Column('required_education', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('typical_skills', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_id'), 'careers', ['id'], unique=False)
    op.create_index(op.f('ix_careers_title'), 'careers', ['title'], unique=True)
    op.create_table('colleges',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colleges_id'), 'colleges', ['id'], unique=False)
    op.create_index(op.f('ix_colleges_name'), 'colleges', ['name'], unique=False)
    op.create_table('degrees',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_degrees_id'), 'degrees', ['id'], unique=False)
    op.create_index(op.f('ix_degrees_name'), 'degrees', ['name'], unique=True)
    op.create_table('entrance_exams',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrance_exams_id'), 'entrance_exams', ['id'], unique=False)
    op.create_index(op.f('ix_entrance_exams_name'), 'entrance_exams', ['name'], unique=True)
    op.create_table('resources',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_title'), 'resources', ['title'], unique=False)
    op.create_table('scholarships',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('deadline', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.create_index(op.f('ix_scholarships_name'), 'scholarships', ['name'], unique=False)
    op.create_table('skills',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('backup_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='backupplanstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_plans_id'), 'backup_plans', ['id'], unique=False)
    op.create_index(op.f('ix_backup_plans_status'), 'backup_plans', ['status'], unique=False)
    op.create_index(op.f('ix_backup_plans_user_id'), 'backup_plans', ['user_id'], unique=False)
    op.create_table('career_colleges',
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('program_name', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'college_id', name='uq_career_college')
    )
    op.create_index(op.f('ix_career_colleges_career_id'), 'career_colleges', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_colleges_college_id'), 'career_colleges', ['college_id'], unique=False)
    op.create_index(op.f('ix_career_colleges_id'), 'career_colleges', ['id'], unique=False)
    op.create_table('career_degrees',
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('degree_id', sa.UUID(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['degree_id'], ['degrees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'degree_id', name='uq_career_degree')
    )
    op.create_index(op.f('ix_career_degrees_career_id'), 'career_degrees', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_degrees_degree_id'), 'career_degrees', ['degree_id'], unique=False)
    op.create_index(op.f('ix_career_degrees_id'), 'career_degrees', ['id'], unique=False)
    op.create_table('career_entrance_exams',
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['entrance_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'exam_id', name='uq_career_exam')
    )
    op.create_index(op.f('ix_career_entrance_exams_career_id'), 'career_entrance_exams', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_entrance_exams_exam_id'), 'career_entrance_exams', ['exam_id'], unique=False)
    op.create_index(op.f('ix_career_entrance_exams_id'), 'career_entrance_exams', ['id'], unique=False)
    op.create_table('career_relations',
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('related_career_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('RELATED', 'ALTERNATIVE', 'PREREQUISITE', 'SUPPLEMENTARY', name='careerrelationtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'related_career_id', 'relation_type', name='uq_career_relation')
    )
    op.create_index(op.f('ix_career_relations_career_id'), 'career_relations', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_relations_id'), 'career_relations', ['id'], unique=False)
    op.create_index(op.f('ix_career_relations_related_career_id'), 'career_relations', ['related_career_id'], unique=False)
    op.create_table('career_resources',
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'resource_id', name='uq_career_resource')
    )
    op.create_index(op.f('ix_career_resources_career_id'), 'career_resources', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_resources_id'), 'career_resources', ['id'], unique=False)
    op.create_index(op.f('ix_career_resources_resource_id'), 'career_resources', ['resource_id'], unique=False)
    op.create_table('career_scholarships',
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('scholarship_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'scholarship_id', name='uq_career_scholarship')
    )
    op.create_index(op.f('ix_career_scholarships_career_id'), 'career_scholarships', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_scholarships_id'), 'career_scholarships', ['id'], unique=False)
    op.create_index(op.f('ix_career_scholarships_scholarship_id'), 'career_scholarships', ['scholarship_id'], unique=False)
    op.create_table('career_skills',
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='skilllevel'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'skill_id', name='uq_career_skill')
    )
    op.create_index(op.f('ix_career_skills_career_id'), 'career_skills', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_skills_id'), 'career_skills', ['id'], unique=False)
    op.create_index(op.f('ix_career_skills_skill_id'), 'career_skills', ['skill_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('skills_used', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_deleted_at'), 'portfolio_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_portfolio_items_id'), 'portfolio_items', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_items_item_type'), 'portfolio_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_portfolio_items_user_id'), 'portfolio_items', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('current_field', sa.String(length=255), nullable=True),
    sa.Column('target_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('interests', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='recommendationstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ARCHIVED', name='roadmapstatus'), nullable=False),
    sa.Column('estimated_duration_months', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_career_id'), 'roadmaps', ['career_id'], unique=False)
    op.create_index(op.f('ix_roadmaps_id'), 'roadmaps', ['id'], unique=False)
    op.create_index(op.f('ix_roadmaps_status'), 'roadmaps', ['status'], unique=False)
    op.create_index(op.f('ix_roadmaps_user_id'), 'roadmaps', ['user_id'], unique=False)
    op.create_table('backup_scenarios',
    sa.Column('backup_plan_id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('scenario_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transition_difficulty', sa.String(length=50), nullable=True),
    sa.Column('estimated_transition_months', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backup_plan_id'], ['backup_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_scenarios_backup_plan_id'), 'backup_scenarios', ['backup_plan_id'], unique=False)
    op.create_index(op.f('ix_backup_scenarios_career_id'), 'backup_scenarios', ['career_id'], unique=False)
    op.create_index(op.f('ix_backup_scenarios_id'), 'backup_scenarios', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chatmessagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('profile_versions',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_versions_id'), 'profile_versions', ['id'], unique=False)
    op.create_table('recommendation_items',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_items_career_id'), 'recommendation_items', ['career_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_id'), 'recommendation_items', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_recommendation_id'), 'recommendation_items', ['recommendation_id'], unique=False)
    op.create_table('roadmap_steps',
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('resources', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_steps_id'), 'roadmap_steps', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_steps_roadmap_id'), 'roadmap_steps', ['roadmap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_steps_roadmap_id'), table_name='roadmap_steps')
    op.drop_index(op.f('ix_roadmap_steps_id'), table_name='roadmap_steps')
    op.drop_table('roadmap_steps')
    op.drop_index(op.f('ix_recommendation_items_recommendation_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_career_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_index(op.f('ix_profile_versions_id'), table_name='profile_versions')
    op.drop_table('profile_versions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_backup_scenarios_id'), table_name='backup_scenarios')
    op.drop_index(op.f('ix_backup_scenarios_career_id'), table_name='backup_scenarios')
    op.drop_index(op.f('ix_backup_scenarios_backup_plan_id'), table_name='backup_scenarios')
    op.drop_table('backup_scenarios')
    op.drop_index(op.f('ix_roadmaps_user_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_status'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_career_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_portfolio_items_user_id'), table_name='portfolio_items')
    op.drop_index(op.f('ix_portfolio_items_item_type'), table_name='portfolio_items')
    op.drop_index(op.f('ix_portfolio_items_id'), table_name='portfolio_items')
    op.drop_index(op.f('ix_portfolio_items_deleted_at'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_career_skills_skill_id'), table_name='career_skills')
    op.drop_index(op.f('ix_career_skills_id'), table_name='career_skills')
    op.drop_index(op.f('ix_career_skills_career_id'), table_name='career_skills')
    op.drop_table('career_skills')
    op.drop_index(op.f('ix_career_scholarships_scholarship_id'), table_name='career_scholarships')
    op.drop_index(op.f('ix_career_scholarships_id'), table_name='career_scholarships')
    op.drop_index(op.f('ix_career_scholarships_career_id'), table_name='career_scholarships')
    op.drop_table('career_scholarships')
    op.drop_index(op.f('ix_career_resources_resource_id'), table_name='career_resources')
    op.drop_index(op.f('ix_career_resources_id'), table_name='career_resources')
    op.drop_index(op.f('ix_career_resources_career_id'), table_name='career_resources')
    op.drop_table('career_resources')
    op.drop_index(op.f('ix_career_relations_related_career_id'), table_name='career_relations')
    op.drop_index(op.f('ix_career_relations_id'), table_name='career_relations')
    op.drop_index(op.f('ix_career_relations_career_id'), table_name='career_relations')
    op.drop_table('career_relations')
    op.drop_index(op.f('ix_career_entrance_exams_id'), table_name='career_entrance_exams')
    op.drop_index(op.f('ix_career_entrance_exams_exam_id'), table_name='career_entrance_exams')
    op.drop_index(op.f('ix_career_entrance_exams_career_id'), table_name='career_entrance_exams')
    op.drop_table('career_entrance_exams')
    op.drop_index(op.f('ix_career_degrees_id'), table_name='career_degrees')
    op.drop_index(op.f('ix_career_degrees_degree_id'), table_name='career_degrees')
    op.drop_index(op.f('ix_career_degrees_career_id'), table_name='career_degrees')
    op.drop_table('career_degrees')
    op.drop_index(op.f('ix_career_colleges_id'), table_name='career_colleges')
    op.drop_index(op.f('ix_career_colleges_college_id'), table_name='career_colleges')
    op.drop_index(op.f('ix_career_colleges_career_id'), table_name='career_colleges')
    op.drop_table('career_colleges')
    op.drop_index(op.f('ix_backup_plans_user_id'), table_name='backup_plans')
    op.drop_index(op.f('ix_backup_plans_status'), table_name='backup_plans')
    op.drop_index(op.f('ix_backup_plans_id'), table_name='backup_plans')
    op.drop_table('backup_plans')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_scholarships_name'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_resources_title'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_entrance_exams_name'), table_name='entrance_exams')
    op.drop_index(op.f('ix_entrance_exams_id'), table_name='entrance_exams')
    op.drop_table('entrance_exams')
    op.drop_index(op.f('ix_degrees_name'), table_name='degrees')
    op.drop_index(op.f('ix_degrees_id'), table_name='degrees')
    op.drop_table('degrees')
    op.drop_index(op.f('ix_colleges_name'), table_name='colleges')
    op.drop_index(op.f('ix_colleges_id'), table_name='colleges')
    op.drop_table('colleges')
    op.drop_index(op.f('ix_careers_title'), table_name='careers')
    op.drop_index(op.f('ix_careers_id'), table_name='careers')
    op.drop_table('careers')

    # Explicitly drop named enum types so downgrade -> upgrade is repeatable.
    for enum_name in (
        "chatmessagerole",
        "skilllevel",
        "careerrelationtype",
        "roadmapstatus",
        "recommendationstatus",
        "backupplanstatus",
        "userrole",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
    # ### end Alembic commands ###
