"""add knowledge base columns to careers

Revision ID: 3a589c75e389
Revises: f4a1b2c3d4e5
Create Date: 2026-07-24 17:04:31.612032
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3a589c75e389'
down_revision: Union[str, None] = 'f4a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('careers', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('careers', sa.Column('industry', sa.String(length=255), nullable=True))
    op.add_column('careers', sa.Column('work_environment', sa.Text(), nullable=True))
    op.add_column('careers', sa.Column('weekly_hours', sa.String(length=50), nullable=True))
    op.add_column('careers', sa.Column('travel_requirement', sa.String(length=100), nullable=True))
    op.add_column('careers', sa.Column('stress_level', sa.String(length=50), nullable=True))
    op.add_column('careers', sa.Column('work_life_balance', sa.String(length=50), nullable=True))
    op.add_column('careers', sa.Column('automation_risk', sa.String(length=100), nullable=True))
    op.add_column('careers', sa.Column('salary_currency', sa.String(length=10), nullable=True))
    op.add_column('careers', sa.Column('entry_level_salary', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('careers', sa.Column('mid_level_salary', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('careers', sa.Column('senior_level_salary', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('careers', sa.Column('highest_salary', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('careers', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_careers_category'), 'careers', ['category'], unique=False)
    op.create_index(op.f('ix_careers_industry'), 'careers', ['industry'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_careers_industry'), table_name='careers')
    op.drop_index(op.f('ix_careers_category'), table_name='careers')
    op.drop_column('careers', 'metadata')
    op.drop_column('careers', 'highest_salary')
    op.drop_column('careers', 'senior_level_salary')
    op.drop_column('careers', 'mid_level_salary')
    op.drop_column('careers', 'entry_level_salary')
    op.drop_column('careers', 'salary_currency')
    op.drop_column('careers', 'automation_risk')
    op.drop_column('careers', 'work_life_balance')
    op.drop_column('careers', 'stress_level')
    op.drop_column('careers', 'travel_requirement')
    op.drop_column('careers', 'weekly_hours')
    op.drop_column('careers', 'work_environment')
    op.drop_column('careers', 'industry')
    op.drop_column('careers', 'category')
    # ### end Alembic commands ###
