#!/usr/bin/env python3
"""Dump the entire Tophexity Postgres DB to a single .sql file.

Writes to docs/db_dumps/tophexity_full_dump.sql (schema + data) and a JSON
table-count summary. Run from repo root.
"""
import os
import sys
import json
import psycopg2
from psycopg2.extras import RealDictCursor

DB_URL = os.environ.get("DATABASE_URL")
if not DB_URL:
    sys.exit("DATABASE_URL env var not set (e.g. postgresql://user:pass@host:5432/db?sslmode=require)")
# psycopg2 needs standard URL scheme
DB_URL = DB_URL.replace("postgresql+asyncpg://", "postgresql://")
DB_URL = DB_URL.replace("?ssl=require", "?sslmode=require")

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "docs", "db_dumps")
os.makedirs(OUT_DIR, exist_ok=True)

# Tables whose data is large/regeneratable ΓÇö keep schema only in core dump.
SKIP_DATA_TABLES = {"document_embeddings"}

MODE = os.environ.get("DUMP_MODE", "full")  # "full" or "core"
suffix = "" if MODE == "full" else "_core"
OUT_SQL = os.path.abspath(os.path.join(OUT_DIR, f"tophexity{suffix}_dump.sql"))
OUT_JSON = os.path.abspath(os.path.join(OUT_DIR, f"tophexity{suffix}_counts.json"))


def q(conn, sql, args=None):
    with conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute(sql, args or ())
        return cur.fetchall()


def main():
    print(f"Connecting to DB ...")
    conn = psycopg2.connect(DB_URL)
    conn.autocommit = True
    print("Connected.")

    # all user tables (exclude alembic if wanted? keep it, it's part of db)
    tables = [r["tablename"] for r in q(
        conn,
        "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY tablename",
    )]
    print(f"Found {len(tables)} tables: {tables}")

    counts = {}
    with open(OUT_SQL, "w", encoding="utf-8") as f:
        f.write("-- Tophexity full database dump\n")
        f.write("-- Generated by dump_db.py\n")
        f.write("-- (schema + data for all public tables)\n\n")
        f.write("SET statement_timeout = 0;\n")
        f.write("SET client_encoding = 'UTF8';\n\n")

        for tbl in tables:
            # row count
            cnt = q(conn, f'SELECT count(*) AS c FROM public."{tbl}"')[0]["c"]
            counts[tbl] = int(cnt)
            print(f"  {tbl}: {cnt} rows")

            # schema
            f.write(f"\n-- ---------- Table: {tbl} ({cnt} rows) ----------\n\n")
            schema_rows = q(
                conn,
                """
                SELECT 'CREATE TABLE ' || relname || ' (' ||
                       array_to_string(array_agg(
                           '    ' || column_name || ' ' || data_type ||
                           COALESCE('(' || character_maximum_length::text || ')', '') ||
                           COALESCE(' ' || column_default, '')
                       ), ',\n') || ');'
                FROM (
                    SELECT c.relname, a.attnum, a.attname AS column_name,
                           format_type(a.atttypid, a.atttypmod) AS data_type,
                           col_description(a.attrelid, a.attnum) AS column_comment,
                           a.attnotnull AS notnull,
                   b.character_maximum_length,
                   pg_get_expr(d.adbin, d.adrelid) AS column_default
                    FROM pg_class c
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    JOIN pg_attribute a ON a.attrelid = c.oid
                    LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
                    LEFT JOIN information_schema.columns b
                      ON b.table_name = c.relname AND b.column_name = a.attname
                      AND b.table_schema = n.nspname
                    WHERE c.relkind = 'r' AND n.nspname = 'public'
                      AND a.attnum > 0 AND NOT a.attisdropped
                      AND c.relname = %s
                    GROUP BY c.relname, a.attnum, a.attname, a.atttypid,
                             a.atttypmod, a.attnotnull, b.character_maximum_length,
                             d.adbin, d.adrelid, a.attrelid
                    ORDER BY a.attnum
                ) s GROUP BY relname;
                """,
                (tbl,),
            )
            if schema_rows:
                f.write(schema_rows[0]["?column?"] + "\n\n")

            # data
            cols = [r["column_name"] for r in q(
                conn,
                """
                SELECT column_name FROM information_schema.columns
                WHERE table_schema='public' AND table_name=%s
                ORDER BY ordinal_position
                """,
                (tbl,),
            )]
            if cnt > 0 and cols and tbl not in SKIP_DATA_TABLES:
                col_list = ", ".join(f'"{c}"' for c in cols)
                with conn.cursor() as cur:
                    cur.execute(f'SELECT {col_list} FROM public."{tbl}"')
                    rows = cur.fetchall()
                    f.write(f"-- Data for {tbl}\n")
                    f.write(f'INSERT INTO "{tbl}" ({col_list}) VALUES\n')
                    val_lines = []
                    for row in rows:
                        vals = []
                        for v in row:
                            if v is None:
                                vals.append("NULL")
                            elif isinstance(v, bool):
                                vals.append("TRUE" if v else "FALSE")
                            elif isinstance(v, (int, float)):
                                vals.append(str(v))
                            else:
                                e = str(v).replace("'", "''")
                                vals.append(f"'{e}'")
                        val_lines.append(f"  ({', '.join(vals)})")
                    f.write(",\n".join(val_lines) + ";\n\n")
            elif tbl in SKIP_DATA_TABLES:
                f.write(f"-- Data for {tbl} SKIPPED (regeneratable via scripts/rebuild_embeddings.py)\n\n")

        # indexes
        f.write("\n-- ---------- Indexes ----------\n\n")
        idx = q(conn, """
            SELECT indexdef FROM pg_indexes WHERE schemaname='public'
            ORDER BY tablename, indexname
        """)
        for r in idx:
            f.write(r["indexdef"] + ";\n")

    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump({"total_tables": len(tables), "tables": counts}, f, indent=2)

    conn.close()
    print(f"\nWrote: {OUT_SQL}")
    print(f"Wrote: {OUT_JSON}")
    total_rows = sum(counts.values())
    print(f"Total tables: {len(tables)}, total rows: {total_rows}")


if __name__ == "__main__":
    main()
